version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: carsties-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: Auctions
      POSTGRES_MULTIPLE_DATABASES: identity,Auctions
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:7
    container_name: carsties-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: carsties-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  auction-svc:
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    image: trycatchlearn/auction-svc:latest
    container_name: carsties-auction-svc
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=postgrespw;Database=Auctions
      - IdentityServiceUrl=http://identity-svc
    ports:
      - "7001:80"
    depends_on:
      - postgres
      - rabbitmq
  search-svc:
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    image: trycatchlearn/search-svc:latest
    container_name: carsties-search-svc
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDBConnection=mongodb://root:mongopw@mongodb:27017
      - AuctionServiceUrl=http://auction-svc
    ports:
      - "7002:80"
    depends_on:
      - mongodb
      - rabbitmq
  identity-svc:
    build:
      context: .
      dockerfile: src/IdentityServer/Dockerfile
    image: trycatchlearn/identity-svc:latest
    container_name: carsties-identity-svc
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=postgrespw;Database=identity
    ports:
      - "5001:80"
    depends_on:
      - postgres
