version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: carsties-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: Auctions
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:7
    container_name: carsties-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: carsties-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbitpw
    ports:
      - "5672:5672"
      - "15672:15672"
